/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframeswing;

/**
 *
 * @author pc
 */
public class BasitHesapMakinesiü extends javax.swing.JFrame {
    private int say=0;
    private boolean artibasildimi=false;
    private boolean eksibasildimi=false;
    private boolean carpibasildimi=false;
    private boolean bolubasildimi=false;
    private String ilksayi="";
    private String ikincisayi="";
    private String operator="";
    /**
     * Creates new form BasitHesapMakinesiü
     */
    public BasitHesapMakinesiü() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonarti = new javax.swing.JButton();
        jButtoneksi = new javax.swing.JButton();
        jButtoncarpi = new javax.swing.JButton();
        jButtonbolu = new javax.swing.JButton();
        jButton01 = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        jButton03 = new javax.swing.JButton();
        jButton04 = new javax.swing.JButton();
        jButton05 = new javax.swing.JButton();
        jButton06 = new javax.swing.JButton();
        jButton07 = new javax.swing.JButton();
        jButton08 = new javax.swing.JButton();
        jButton09 = new javax.swing.JButton();
        jButton00 = new javax.swing.JButton();
        Hesapla = new javax.swing.JButton();
        Arayuz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonarti.setText("+");
        jButtonarti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonartiActionPerformed(evt);
            }
        });

        jButtoneksi.setText(" -");
        jButtoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneksiActionPerformed(evt);
            }
        });

        jButtoncarpi.setText("x");
        jButtoncarpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncarpiActionPerformed(evt);
            }
        });

        jButtonbolu.setText("/");
        jButtonbolu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonboluActionPerformed(evt);
            }
        });

        jButton01.setText("1");
        jButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton01ActionPerformed(evt);
            }
        });

        jButton02.setText("2");
        jButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton02ActionPerformed(evt);
            }
        });

        jButton03.setText("3");
        jButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton03ActionPerformed(evt);
            }
        });

        jButton04.setText("4");
        jButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton04ActionPerformed(evt);
            }
        });

        jButton05.setText("5");
        jButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton05ActionPerformed(evt);
            }
        });

        jButton06.setText("6");
        jButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton06ActionPerformed(evt);
            }
        });

        jButton07.setText("7");
        jButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton07ActionPerformed(evt);
            }
        });

        jButton08.setText("8");
        jButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton08ActionPerformed(evt);
            }
        });

        jButton09.setText("9");
        jButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton09ActionPerformed(evt);
            }
        });

        jButton00.setText("0");
        jButton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton00ActionPerformed(evt);
            }
        });

        Hesapla.setText("Hesapla");
        Hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HesaplaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Arayuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jButton07, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton05, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton08, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonbolu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtoneksi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonarti))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtoncarpi)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Arayuz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonarti)
                    .addComponent(jButton01)
                    .addComponent(jButton02)
                    .addComponent(jButton03))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoneksi)
                    .addComponent(jButton04)
                    .addComponent(jButton05)
                    .addComponent(jButton06))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoncarpi)
                    .addComponent(jButton07)
                    .addComponent(jButton08)
                    .addComponent(jButton09))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonbolu)
                    .addComponent(jButton00))
                .addGap(7, 7, 7)
                .addComponent(Hesapla, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneksiActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi==false && artibasildimi==false && bolubasildimi==false && carpibasildimi==false){
            eksibasildimi=true;
        }
        
    }//GEN-LAST:event_jButtoneksiActionPerformed

    private void jButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton01ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="1";
        }
        else{
            ikincisayi+="1";
        }
    }//GEN-LAST:event_jButton01ActionPerformed

    private void jButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton02ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="2";
        }
        else{
            ikincisayi+="2";
        }
    }//GEN-LAST:event_jButton02ActionPerformed

    private void jButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton03ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="3";
        }
        else{
            ikincisayi+="3";
        }
    }//GEN-LAST:event_jButton03ActionPerformed

    private void jButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton04ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="4";
        }
        else{
            ikincisayi+="4";
        }
    }//GEN-LAST:event_jButton04ActionPerformed

    private void jButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton05ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="5";
        }
        else{
            ikincisayi+="5";
        }
    }//GEN-LAST:event_jButton05ActionPerformed

    private void jButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton06ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="6";
        }
        else{
            ikincisayi+="6";
        }
    }//GEN-LAST:event_jButton06ActionPerformed

    private void jButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton07ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="7";
        }
        else{
            ikincisayi+="7";
        }
    }//GEN-LAST:event_jButton07ActionPerformed

    private void jButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton08ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="8";
        }
        else{
            ikincisayi+="8";
        }
    }//GEN-LAST:event_jButton08ActionPerformed

    private void jButton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton09ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="9";
        }
        else{
            ikincisayi+="9";
        }
    }//GEN-LAST:event_jButton09ActionPerformed

    private void jButton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton00ActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi!=false || artibasildimi!=false || bolubasildimi!=false || carpibasildimi!=false){
            ilksayi+="0";
        }
        else{
            ikincisayi+="0";
        }
    }//GEN-LAST:event_jButton00ActionPerformed

    private void jButtonartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonartiActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi==false && artibasildimi==false && bolubasildimi==false && carpibasildimi==false){
            artibasildimi=true;
        }
    }//GEN-LAST:event_jButtonartiActionPerformed

    private void jButtoncarpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncarpiActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi==false && artibasildimi==false && bolubasildimi==false && carpibasildimi==false){
            carpibasildimi=true;
        }
    }//GEN-LAST:event_jButtoncarpiActionPerformed

    private void jButtonboluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonboluActionPerformed
        // TODO add your handling code here:
        if(eksibasildimi==false && artibasildimi==false && bolubasildimi==false && carpibasildimi==false){
            bolubasildimi=true;
        }
    }//GEN-LAST:event_jButtonboluActionPerformed

    private void HesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HesaplaActionPerformed
        // TODO add your handling code here:
        long sonuc=0;
        if(artibasildimi){
            sonuc=Integer.parseInt(ilksayi)+Integer.parseInt(ikincisayi);
            artibasildimi=false;
        }
        if(eksibasildimi){
            sonuc=Integer.parseInt(ilksayi)-Integer.parseInt(ikincisayi);
            eksibasildimi=false;
        }
        if(bolubasildimi){
            sonuc=Integer.parseInt(ilksayi)/Integer.parseInt(ikincisayi);
            bolubasildimi=false;
        }
        if(carpibasildimi){
            sonuc=Integer.parseInt(ilksayi)*Integer.parseInt(ikincisayi);
            carpibasildimi=false;
        }
        Arayuz.setText(String.valueOf(sonuc));
    }//GEN-LAST:event_HesaplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasitHesapMakinesiü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasitHesapMakinesiü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasitHesapMakinesiü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasitHesapMakinesiü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasitHesapMakinesiü().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arayuz;
    private javax.swing.JButton Hesapla;
    private javax.swing.JButton jButton00;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton03;
    private javax.swing.JButton jButton04;
    private javax.swing.JButton jButton05;
    private javax.swing.JButton jButton06;
    private javax.swing.JButton jButton07;
    private javax.swing.JButton jButton08;
    private javax.swing.JButton jButton09;
    private javax.swing.JButton jButtonarti;
    private javax.swing.JButton jButtonbolu;
    private javax.swing.JButton jButtoncarpi;
    private javax.swing.JButton jButtoneksi;
    // End of variables declaration//GEN-END:variables
}
