/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stokuygulamasi;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class StockApp extends javax.swing.JFrame {

    /**
     * Creates new form StockApp
     */
    public StockApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        urunAdiGir = new javax.swing.JTextField();
        urunFiyatiGiriniz = new javax.swing.JTextField();
        db_kategori = new javax.swing.JComboBox<>();
        mesaj_yazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        ekle_butonu = new javax.swing.JButton();
        urunGuncelle = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün İsmi:");

        jLabel2.setText("Kategori:");

        jLabel3.setText("Fiyat:");

        urunFiyatiGiriniz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunFiyatiGirinizActionPerformed(evt);
            }
        });

        db_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür Sanat", "Yemek", "Elektronik" }));

        mesaj_yazisi.setForeground(new java.awt.Color(255, 51, 51));

        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Kategori", "Fiyat"
            }
        ));
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);

        ekle_butonu.setText("Ürün Ekle");
        ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonuActionPerformed(evt);
            }
        });

        urunGuncelle.setText("Ürün Güncelle");
        urunGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunGuncelleActionPerformed(evt);
            }
        });

        deleteButton.setText("Ürün Sil");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(urunGuncelle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(urunAdiGir)
                            .addComponent(db_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunFiyatiGiriniz, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ekle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(urunAdiGir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(db_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(urunFiyatiGiriniz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekle_butonu)
                    .addComponent(urunGuncelle)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urunFiyatiGirinizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunFiyatiGirinizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunFiyatiGirinizActionPerformed

    private void ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonuActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        DefaultTableModel model=(DefaultTableModel) urun_tablosu.getModel();
        if (urunAdiGir.getText().trim().equals("")) {
            mesaj_yazisi.setText("Ürün ismi boş bırakılamaz");
        }
        else{
            Object[] eklenecek={urunAdiGir.getText(),db_kategori.getSelectedItem().toString(),urunFiyatiGiriniz.getText()};
            model.addRow(eklenecek);
        }
    }//GEN-LAST:event_ekle_butonuActionPerformed

    private void urunGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunGuncelleActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        DefaultTableModel model=(DefaultTableModel) urun_tablosu.getModel();
        int secili_row=urun_tablosu.getSelectedRow();
        if (secili_row==-1) {
            if (urun_tablosu.getRowCount()==0) {
                mesaj_yazisi.setText("Ürün tablosu şu an boş...");
            }else{
                mesaj_yazisi.setText("Lütfen güncellenecek bir ürün seçiniz");
                
            }
        }else{
            model.setValueAt(urunAdiGir.getText(), secili_row, 0);
            model.setValueAt(db_kategori.getSelectedItem().toString(), secili_row, 1);
            model.setValueAt(urunFiyatiGiriniz.getText(), secili_row, 2);
            mesaj_yazisi.setText("Ürün Başarıyla Güncellendi");
        }
    }//GEN-LAST:event_urunGuncelleActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) urun_tablosu.getModel();
        int seciliRow=urun_tablosu.getSelectedRow();
        urunAdiGir.setText(model.getValueAt(seciliRow,0).toString());
        db_kategori.setSelectedItem(model.getValueAt(seciliRow,1).toString());
        urunFiyatiGiriniz.setText(model.getValueAt(seciliRow,2).toString());
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        DefaultTableModel model=(DefaultTableModel) urun_tablosu.getModel();
        int secili_row=urun_tablosu.getSelectedRow();
        if (secili_row==-1) {
            if (urun_tablosu.getRowCount()==0) {
                mesaj_yazisi.setText("Ürün tablosu şu an boş...");
            }else{
                mesaj_yazisi.setText("Lütfen silinecek bir ürün seçiniz");
                
            }
        }else{
            model.removeRow(secili_row);
            mesaj_yazisi.setText("Ürün Başarıyla Silindi");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> db_kategori;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton ekle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField urunAdiGir;
    private javax.swing.JTextField urunFiyatiGiriniz;
    private javax.swing.JButton urunGuncelle;
    private javax.swing.JTable urun_tablosu;
    // End of variables declaration//GEN-END:variables
}
